apiVersion: batch/v1
kind: Job
metadata:
  name: populate-web-content
spec:
  template:
    spec:
      containers:
      - name: alpine
        image: alpine:latest
        command: ["sh", "-c", "echo 'Hello from NFS!' > /mnt/nfs/index.html"]
        volumeMounts:
        - name: web-content
          mountPath: /mnt/nfs
      restartPolicy: OnFailure
      volumes:
      - name: web-content
        persistentVolumeClaim:
          claimName: nfs-pvc
